# Generated by Django 4.2 on 2024-10-29 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('rut', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sector', models.CharField(choices=[('CE', 'Centro'), ('AM', 'Amanecer'), ('EC', 'El Carmen'), ('LA', 'Labranza'), ('PV', 'Pedro de Valdivia'), ('PO', 'Poniente'), ('PN', 'Pueblo Nuevo'), ('SR', 'Santa Rosa')], default='CE', max_length=2)),
                ('direccion', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('telefono', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(8)])),
                ('nacionalidad', models.CharField(choices=[('CL', 'Chileno'), ('EX', 'Extranjero')], default='CL', max_length=2)),
                ('autorizado', models.BooleanField(default=False)),
                ('contraseña', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
