# Generated by Django 4.2 on 2024-10-29 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_userdata_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
