# Generated by Django 4.2 on 2024-10-29 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_alter_userdata_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='rut',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
