# Generated by Django 4.2 on 2024-10-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_alter_userdata_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='contraseña',
        ),
    ]
