# Generated by Django 4.2 on 2024-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_remove_userdata_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='fotoperfil',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
