# Generated by Django 4.2 on 2024-10-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20, null=True)),
                ('cuerpo', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
