# Generated by Django 4.2 on 2024-10-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='telefono',
        ),
    ]
