# Generated by Django 4.2 on 2024-10-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0002_remove_notificaciones_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='privilegios',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='rut',
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='cuerpo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='titulo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
