# Generated by Django 4.2 on 2024-10-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosubido',
            name='fecha_subida',
        ),
    ]
