# Generated by Django 4.2 on 2024-09-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipales',
            name='privilegios',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='municipales',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
    ]
