# Generated by Django 4.2 on 2024-10-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipales', '0003_municipales_contraseña_alter_municipales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipales',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
