# Generated by Django 4.2 on 2024-10-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipales', '0004_alter_municipales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipales',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
