# Generated by Django 4.2 on 2024-10-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sector', models.CharField(max_length=50)),
                ('hora', models.TimeField()),
                ('atencionAsistencia', models.BooleanField()),
                ('atencionTipo', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('trabajo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('fotoperfil', models.FileField(null=True, upload_to='archivos/')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('disponibilidad', models.DateField()),
                ('prestadorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.prestadorservicio')),
            ],
        ),
    ]
