# Generated by Django 4.2 on 2024-10-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorservicio',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
