# Generated by Django 4.2 on 2024-10-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
