# Generated by Django 4.2 on 2024-10-29 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atencion',
            name='servicioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicio'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.prestadorservicio'),
        ),
    ]
