# Generated by Django 4.2 on 2024-10-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_prestadorservicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadorservicio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
