# Generated by Django 4.2 on 2024-10-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_alter_atencion_clienteid_delete_usuario'),
        ('Servicios', '0004_asistencia'),
    ]

    operations = [
    ]
