# Generated by Django 4.2 on 2024-10-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_merge_20241020_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorservicio',
            name='fotoperfil',
            field=models.FileField(null=True, upload_to='archivos/'),
        ),
    ]
